version: '3.3'
services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'LuckyShineDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  lucky-shine-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - db
    environment:
      DB_HOST: db
    restart: unless-stopped
    container_name: lucky-shine-api
    volumes:
      - ./api/node_modules:/usr/src/app/node_modules
    networks:
      lucky-shine-network:
        aliases:
          - lucky-shine-api


networks:
  lucky-shine-network: