version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      valiu-network:

networks:
  valiu-network:

volumes:
  data: