version: '3.7'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      valiu-network:

  rabbitmq3:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    volumes:
      - data:/var/lib/rabbitmq
    networks:
      valiu-network:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      valiu-network:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3004:3004
    networks:
      valiu-network:

networks:
  valiu-network:

volumes:
  data: